import { Contact, Memory } from '../types';

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'rohan-mehta',
    name: 'Rohan Mehta',
    role: 'VP Operations',
    org: 'Kridha Logistics',
    category: 'clients',
    lastMeeting: 'Yesterday',
    hasFollowup: true,
    followupSummary: 'Scaling to 10 warehouses rollout plan',
    location: 'Mumbai / Pune',
    email: 'rohan.mehta@kridhalogistics.com',
    directReports: 42,
    engagementScore: 91,
    cadence: 'Bi-weekly',
    statusText: '10-warehouse expansion proposal due',
    isPriority: true,
    meetingLink: 'https://meet.google.com/kri-dhaa-log',
  },
  {
    id: 'ananya-iyer',
    name: 'Ananya Iyer',
    role: 'Founder & CEO',
    org: 'Saffron & Co.',
    category: 'clients',
    lastMeeting: '4 days ago',
    hasFollowup: true,
    followupSummary: 'Draft 3-month trial agreement',
    location: 'Bengaluru',
    email: 'ananya@saffronandco.in',
    directReports: 15,
    engagementScore: 84,
    cadence: 'Weekly',
    statusText: '3-month trial term sheet awaiting signoff',
    isPriority: false,
    meetingLink: 'https://zoom.us/j/9876543210',
  },
  {
    id: 'arjun-nair',
    name: 'Arjun Nair',
    role: 'IT Manager',
    org: 'Suryodaya Financial Services',
    category: 'advisory',
    lastMeeting: 'Oct 12',
    hasFollowup: false,
    followupSummary: 'Internal training roadmap aligned',
    location: 'Hyderabad',
    email: 'arjun.nair@suryodayafin.com',
    directReports: 8,
    engagementScore: 78,
    cadence: 'Monthly',
    statusText: 'Legal cleared SOC 2; implementation scheduled',
    isPriority: false,
    meetingLink: 'https://meet.google.com/sur-ydya-fin',
  },
  {
    id: 'eleanor-vance',
    name: 'Eleanor Vance',
    role: 'VP Procurement',
    org: 'Meridian Capital',
    category: 'clients',
    lastMeeting: 'Oct 18',
    hasFollowup: true,
    followupSummary: 'Draft SLA schedule & liability cap terms',
    location: 'London / Zurich',
    email: 'e.vance@meridiancapital.ch',
    directReports: 18,
    engagementScore: 94,
    cadence: 'Bi-weekly',
    statusText: 'Pending brief approval on liability caps',
    isPriority: true,
    meetingLink: 'https://meet.google.com/mer-idia-n4c',
  },
  {
    id: 'marcus-thorne',
    name: 'Marcus Thorne',
    role: 'Managing Director',
    org: 'Halcyon Partners',
    category: 'advisory',
    lastMeeting: 'Oct 12',
    hasFollowup: false,
    followupSummary: 'Closed terms ratified',
    location: 'New York',
    email: 'mthorne@halcyonpartners.com',
    directReports: 12,
    engagementScore: 88,
    cadence: 'Quarterly',
    statusText: 'Closed terms for Q4 co-investment',
    isPriority: false,
    meetingLink: 'https://zoom.us/j/8812345678',
  },
  {
    id: 'julian-vance-croft',
    name: 'Julian Vance-Croft',
    role: 'Partner',
    org: 'Horizon Ventures',
    category: 'advisory',
    lastMeeting: 'Never',
    hasFollowup: false,
    followupSummary: 'No historical debriefs logged yet',
    location: 'San Francisco',
    email: 'julian@horizonvc.com',
    directReports: 5,
    engagementScore: 0,
    cadence: 'Pending First Sync',
    statusText: 'Pending initial briefing intake',
    isPriority: false,
    meetingLink: 'https://meet.google.com/hrz-onvc-sfb',
  }
];

export const INITIAL_MEMORIES: Memory[] = [
  // Rohan Mehta memories (5 meetings)
  {
    id: 'rm-mem-1',
    contactId: 'rohan-mehta',
    timestamp: '2026-08-10T10:00:00Z',
    displayDate: 'Aug 10, 2026',
    title: 'Initial Onboarding Timeline & Cost Scoping',
    content: 'Discussed onboarding timeline for Kridha logistics fleet management. Rohan raised significant concern regarding API integration cost and legacy TMS integration complexity.',
    type: 'discussion',
    keyFact: 'concerned about API integration cost',
    speaker: 'Rohan Mehta',
    subject: 'Integration Budgets',
    durationMinutes: 45,
    confidence: 0.95
  },
  {
    id: 'rm-mem-2',
    contactId: 'rohan-mehta',
    timestamp: '2026-08-24T14:30:00Z',
    displayDate: 'Aug 24, 2026',
    title: 'Integration Cost Follow-up',
    content: 'Followed up on integration cost architecture. We promised a revised quote by end of week with tiered discounting based on volume.',
    type: 'promise',
    keyFact: 'promised a revised quote by end of week',
    speaker: 'Our Team',
    subject: 'Revised Pricing Proposal',
    durationMinutes: 30,
    confidence: 0.97
  },
  {
    id: 'rm-mem-3',
    contactId: 'rohan-mehta',
    timestamp: '2026-09-07T11:00:00Z',
    displayDate: 'Sep 07, 2026',
    title: 'Data Security Compliance Inquiries',
    content: 'Rohan asked about data security compliance, cloud residency for telematics, and encryption at rest. Quote was still pending his CFO review.',
    type: 'discussion',
    keyFact: 'telematics data residency compliance',
    speaker: 'Rohan Mehta',
    subject: 'Data Governance',
    durationMinutes: 40,
    confidence: 0.92
  },
  {
    id: 'rm-mem-4',
    contactId: 'rohan-mehta',
    timestamp: '2026-09-18T16:00:00Z',
    displayDate: 'Sep 18, 2026',
    title: 'Commercial Terms Cleared & Pilot Proposal',
    content: 'Confirmed pricing accepted after revised schedule. Rohan requested a controlled pilot with 2 distribution warehouses first before broad commitment.',
    type: 'discussion',
    keyFact: 'pilot with 2 warehouses first',
    speaker: 'Rohan Mehta',
    subject: 'Pilot Scope',
    durationMinutes: 50,
    confidence: 0.98
  },
  {
    id: 'rm-mem-5',
    contactId: 'rohan-mehta',
    timestamp: '2026-09-28T09:30:00Z',
    displayDate: 'Sep 28, 2026',
    title: 'Pilot Review & Multi-Site Scaling',
    content: 'Pilot review meeting. Received highly positive feedback on 99.8% uptime during peak sorting hours. Rohan asked about scaling to 10 warehouses across Western India.',
    type: 'followup',
    keyFact: 'asked about scaling to 10 warehouses',
    speaker: 'Rohan Mehta',
    subject: 'Expansion Rollout',
    durationMinutes: 45,
    confidence: 0.99
  },

  // Ananya Iyer memories (4 meetings)
  {
    id: 'ai-mem-1',
    contactId: 'ananya-iyer',
    timestamp: '2026-08-15T15:00:00Z',
    displayDate: 'Aug 15, 2026',
    title: 'Customer Support Automation Exploration',
    content: 'Ananya is interested in the product for customer support automation at Saffron & Co. Highly budget-conscious as an early-stage D2C brand.',
    type: 'discussion',
    keyFact: 'budget-conscious customer support automation',
    speaker: 'Ananya Iyer',
    subject: 'Cost Efficiency',
    durationMinutes: 40,
    confidence: 0.93
  },
  {
    id: 'ai-mem-2',
    contactId: 'ananya-iyer',
    timestamp: '2026-08-29T11:00:00Z',
    displayDate: 'Aug 29, 2026',
    title: 'WhatsApp Integration & Benchmark Comparison',
    content: 'Asked about WhatsApp Business API integration specifically. Mentioned a competitor offering lower entry pricing with usage-based charges.',
    type: 'discussion',
    keyFact: 'WhatsApp integration and competitor pricing comparison',
    speaker: 'Ananya Iyer',
    subject: 'Channel Capabilities',
    durationMinutes: 35,
    confidence: 0.94
  },
  {
    id: 'ai-mem-3',
    contactId: 'ananya-iyer',
    timestamp: '2026-09-12T14:00:00Z',
    displayDate: 'Sep 12, 2026',
    title: 'Case Study Request for D2C Brands',
    content: 'Requested case studies from similar-sized D2C e-commerce brands showing reduction in first-response times and return request deflection.',
    type: 'promise',
    keyFact: 'providing case studies from similar-sized D2C brands',
    speaker: 'Our Team',
    subject: 'Proof of ROI',
    durationMinutes: 30,
    confidence: 0.96
  },
  {
    id: 'ai-mem-4',
    contactId: 'ananya-iyer',
    timestamp: '2026-09-25T10:00:00Z',
    displayDate: 'Sep 25, 2026',
    title: 'Trial Structure & Pilot Agreement',
    content: 'Ready to move forward, but asked for a 3-month trial period instead of an annual commitment to validate peak holiday season conversion.',
    type: 'followup',
    keyFact: '3-month trial period instead of annual commitment',
    speaker: 'Ananya Iyer',
    subject: 'Contract Structure',
    durationMinutes: 45,
    confidence: 0.98
  },

  // Arjun Nair memories (3 meetings)
  {
    id: 'an-mem-1',
    contactId: 'arjun-nair',
    timestamp: '2026-08-05T11:30:00Z',
    displayDate: 'Aug 05, 2026',
    title: 'Data Privacy & Banking Compliance Scrutiny',
    content: 'Arjun is very cautious about customer financial data privacy. Asked detailed compliance questions on RBI guidelines and local auditing.',
    type: 'discussion',
    keyFact: 'cautious about financial data privacy and compliance',
    speaker: 'Arjun Nair',
    subject: 'Regulatory Governance',
    durationMinutes: 60,
    confidence: 0.96
  },
  {
    id: 'an-mem-2',
    contactId: 'arjun-nair',
    timestamp: '2026-08-28T16:00:00Z',
    displayDate: 'Aug 28, 2026',
    title: 'Legal Escalation & SOC 2 Verification',
    content: 'Escalated privacy concerns to Suryodaya legal team. Requested unredacted SOC 2 Type II documentation and penetration testing audit trails.',
    type: 'promise',
    keyFact: 'delivering unredacted SOC 2 documentation to legal',
    speaker: 'Our Team',
    subject: 'Audit Validation',
    durationMinutes: 45,
    confidence: 0.97
  },
  {
    id: 'an-mem-3',
    contactId: 'arjun-nair',
    timestamp: '2026-09-17T13:00:00Z',
    displayDate: 'Sep 17, 2026',
    title: 'Legal Clearance & Implementation Sequencing',
    content: 'Suryodaya legal cleared the audit pack. Arjun is now focused on implementation timeline, staff enablement, and internal training needs.',
    type: 'followup',
    keyFact: 'implementation timeline and internal training needs',
    speaker: 'Arjun Nair',
    subject: 'Enablement Strategy',
    durationMinutes: 50,
    confidence: 0.99
  },

  // Eleanor Vance memories (5 meetings matching screenshots)
  {
    id: 'ev-mem-1',
    contactId: 'eleanor-vance',
    timestamp: '2024-05-03T10:00:00Z',
    displayDate: 'May 03, 2024',
    title: 'Vendor Onboarding & Security Architecture Review',
    content: 'Vendor onboarding and security architecture review. Eleanor made clear that compliance velocity is her top metric over price concessions.',
    type: 'discussion',
    keyFact: 'compliance velocity over pricing concessions',
    speaker: 'Eleanor Vance',
    subject: 'Procurement Strategy',
    durationMinutes: 50,
    confidence: 0.94
  },
  {
    id: 'ev-mem-2',
    contactId: 'eleanor-vance',
    timestamp: '2024-07-14T14:00:00Z',
    displayDate: 'Jul 14, 2024',
    title: 'Initial Enterprise Pilot Readout & SLA Review',
    content: 'Initial enterprise pilot readout and SLA review. Meridian noted sensitivity around maintenance downtime windows in European timezones.',
    type: 'discussion',
    keyFact: 'sensitivity around SLA maintenance windows',
    speaker: 'Eleanor Vance',
    subject: 'SLA Guardrails',
    durationMinutes: 30,
    confidence: 0.95
  },
  {
    id: 'ev-mem-3',
    contactId: 'eleanor-vance',
    timestamp: '2024-08-14T11:00:00Z',
    displayDate: 'Aug 14, 2024',
    title: 'Data Sovereignty & Frankfurt Hosting Verification',
    content: 'Discussed EU data residency addendum. We promised to coordinate with Frankfurt AWS eu-central-1 team to ensure audit isolation under Annex D.',
    type: 'followup',
    keyFact: 'EU data residency addendum awaiting counterparty legal',
    speaker: 'Our Team',
    subject: 'Jurisdiction Agreement',
    durationMinutes: 45,
    confidence: 0.96
  },
  {
    id: 'ev-mem-4',
    contactId: 'eleanor-vance',
    timestamp: '2024-09-22T15:30:00Z',
    displayDate: 'Sep 22, 2024',
    title: 'Penetration Audit Verification & Legal Debrief',
    content: 'Penetration audit verification and legal debrief. We committed to delivering the unredacted penetration test report prior to final board sign-off.',
    type: 'promise',
    keyFact: 'delivering unredacted penetration test report',
    speaker: 'Our Team',
    subject: 'Penetration Audit',
    durationMinutes: 60,
    confidence: 0.98
  },
  {
    id: 'ev-mem-5',
    contactId: 'eleanor-vance',
    timestamp: '2024-10-18T16:00:00Z',
    displayDate: 'Oct 18, 2024',
    title: 'Scope Alignment & Indemnity Cap Review',
    content: 'Discussed revised liability caps. Eleanor insisted on capping indemnity at 2x annual recurring fee rather than 3x. Expect SOC 2 verification request before signing.',
    type: 'discussion',
    keyFact: 'capping indemnity at 2x annual recurring fee',
    speaker: 'Eleanor Vance',
    subject: 'Liability Limitations',
    durationMinutes: 45,
    confidence: 0.99
  }
];
